---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: trtlab-s3
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
  dataPool:
    failureDomain: host
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    securePort:
    instances: 1
    allNodes: false
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: trtlab
  namespace: rook-ceph
spec:
  store: trtlab-s3
  displayName: "TensorRT Laboratory"
